version: "3.3"
services:
  backend: &python
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT:-8000}:8000"
    volumes:
      - ./:/app
    command: python src/main.py
    logging:
      options:
        max-size: "10m"
        max-file: "3"


