import logging


class HealthCheckFilter(logging.Filter):
    """
    A class for logging filter that ignores log records generated by health check requests.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        """
        Filters out log records generated by health check requests.
        
        Arguments:
        -----------
        record: logging.LogRecord
            The log record to be filtered.
            
        Returns:
        --------
        bool:
            Returns False if the request path in the log record matches "/api/v1/health/",
            True otherwise.
        """
        return record.args[2] != "/api/v1/health/"


LOGGING_CONFIG: dict = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "healthCheckFilter": {
            "()": HealthCheckFilter,
        }
    },
    "formatters": {
        "default": {
            "()": "src.logging.formatter.CustomFormatter",
            "fmt": "%(levelprefix)s %(asctime)s %(filename)s %(line)s %(in_func)s %(funcName)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "uvicorn": {
            "()": "src.logging.formatter.AccessFormatter",
            "fmt": "%(levelprefix)s %(asctime)s %(client_addr)s %(request_line)s %(status_code)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "default": {
            "formatter": "default",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
        },
        "uvicorn": {
            "formatter": "uvicorn",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "root": {"handlers": ["default"], "level": "INFO"},
        "uvicorn": {"handlers": ["default"], "level": "INFO"},
        "uvicorn.error": {"handlers": ["default"], "level": "INFO", "propagate": False},
        "celery.app.trace": {"handlers": [], "level": "INFO", "propagate": False},
        "celery.worker.strategy": {"handlers": [], "level": "INFO", "propagate": False},
        "uvicorn.access": {
            "handlers": ["uvicorn"],
            "level": "INFO",
            "propagate": False,
            "filters": ["healthCheckFilter"],
        },
    },
}
